//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterChalanDetail
    {
        public int Id { get; set; }
        public int chalan_id { get; set; }
        public int product_id { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> Fold { get; set; }
        public Nullable<int> ExpectedFold { get; set; }
        public Nullable<decimal> NetQuantity { get; set; }
        public Nullable<decimal> Shrinkage { get; set; }
        public string Description { get; set; }
    
        public virtual PrinterChalan PrinterChalan { get; set; }
        public virtual Product Product { get; set; }
    }
}
