//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public int product_id { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Type { get; set; }
        public Nullable<int> ReferenceRecordId { get; set; }
        public Nullable<int> FinancialYear_Id { get; set; }
        public int Company_Id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual FinancialYear FinancialYear { get; set; }
        public virtual Product Product { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
