//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_ledger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_ledger()
        {
            this.acc_transactions_details = new HashSet<acc_transactions_details>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int Company_Id { get; set; }
        public int group_id { get; set; }
    
        public virtual acc_group acc_group { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_transactions_details> acc_transactions_details { get; set; }
    }
}
