//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_transactions_details
    {
        public int id { get; set; }
        public int voucher_id { get; set; }
        public string trans_type { get; set; }
        public decimal amount { get; set; }
        public int acc_ledger_id { get; set; }
        public string description { get; set; }
    
        public virtual acc_ledger acc_ledger { get; set; }
        public virtual acc_transactions acc_transactions { get; set; }
    }
}
