//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PurchaseDetail
    {
        public int Id { get; set; }

        [ForeignKey("PurchaseOrder")]
        public int PurchaseId { get; set; }

        [ForeignKey("Product")]
        public int product_id { get; set; }
        public decimal Quantity { get; set; }
        public int Fold { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
