//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TailorChalanSend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TailorChalanSend()
        {
            this.TailorChalanSendDetails = new HashSet<TailorChalanSendDetail>();
            this.TailorChalanSendDetails1 = new HashSet<TailorChalanSendDetail>();
        }
    
        public int Id { get; set; }

        [ForeignKey("Vendor")]
        public int vendor_id { get; set; }
        public System.DateTime ChalanDate { get; set; }
        public Nullable<int> ChalanNo { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Description { get; set; }
        public string bill_number { get; set; }

        [ForeignKey("User")]
        public Nullable<int> created_by_id { get; set; }
        [ForeignKey("FinancialYear")]
        public Nullable<int> FinancialYear_Id { get; set; }

        [ForeignKey("Company")]
        public int Company_Id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual FinancialYear FinancialYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TailorChalanSendDetail> TailorChalanSendDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TailorChalanSendDetail> TailorChalanSendDetails1 { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}
